# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir "mcp[cli]>=1.5.0" httpx

# Default command to start the MCP server
CMD ["python", "aptos_mcp_server.py"]
